### PR TITLE
Revert "Deleted duplicated code and fixed compile warnings."

### PR DESCRIPTION
**Pull request by CoqRogue**
Reverts NordicSemiconductor/pc-nrfjprog-js#2

### CODE REVIEW

**Comment by CoqRogue** [comment]
These need to stay in sync with nrfjprog implementation of these files.

**Comment by bencefr** [comment]
Why does it need to stay in sync? Or why nrfjprog cannot be fixed the same way? I don't see the reason why a better code should be reverted to be in sync with a bad implementation.

**Comment by CoqRogue** [comment]
These files will probably be removed with the new version of pc-nrfjprog-js anyway, but the advantage with staying in sync with them is higher than removing the compile warnings in my opinion. We could get SAG to update their code, but lets do that after we figure out which parts of this code we need.

**Comment by bencefr** [comment]
This is not convincing. I can't see how staying in sync has any advantage unless you foresee high maintenance costs. I would keep the fixed code until it will be removed.

**Pull request closed without merging**
